language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

#create and tag the docker image
script:
  - docker --version # print the version for logging
  - docker build -t simple-express .
  - docker tag simple-express emanana/simple-express:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push emanana/simple-express

