apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector: 8080
    service: reverseproxy